DEBUG 2022-12-31 12:58:20.209 UTC: 	 CRAB Client version: v3.221018
DEBUG 2022-12-31 12:58:20.209 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-12-31 12:58:20.209 UTC: 	 Executing command: 'submit'
DEBUG 2022-12-31 12:58:20.210 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adlintul/.crab3
INFO 2022-12-31 12:58:20.210 UTC: 	 Will use CRAB configuration file ZH_HToBB_ZToNuNu_M-125_TuneCP5_13TeV-powheg-pythia8.py
DEBUG 2022-12-31 12:58:20.211 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-12-31 12:58:20.280 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2022-12-31 12:58:20.280 UTC: 	 Working area '/afs/cern.ch/work/a/adlintul/public/scouting/hbb/gridpack/CMSSW_12_4_11_patch1/src/SampleGeneration/Analysis/run/crab_projects/crab_ZH_HToBB_ZToNuNu_M-125_TuneCP5_13TeV-powheg-pythia8' already exists 
Please change the requestName in the config file
ERROR 2022-12-31 12:58:20.281 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.221018.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/work/a/adlintul/public/scouting/hbb/gridpack/CMSSW_12_4_11_patch1/src/SampleGeneration/Analysis/run/crab_projects/crab_ZH_HToBB_ZToNuNu_M-125_TuneCP5_13TeV-powheg-pythia8' already exists 
Please change the requestName in the config file
INFO 2022-12-31 12:58:20.284 UTC: 	 Log file is /afs/cern.ch/work/a/adlintul/public/scouting/hbb/gridpack/CMSSW_12_4_11_patch1/src/SampleGeneration/Analysis/run/crab.log
